# Netlify 빌드 설정
[build]
  # 빌드 명령
  command = "npm run build"
  # 빌드 결과물 디렉토리
  publish = "dist"

# SPA 라우팅 설정 (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 환경 변수 (민감 정보는 Netlify Dashboard에서 설정)
[build.environment]
  NODE_VERSION = "20"
