[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install --prefer-offline --no-audit --legacy-peer-deps']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npx serve dist -l $PORT'
