version: '3.8'

services:
  # Redis (캐싱 및 Pub/Sub)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Stream Service (실시간 주가)
  stream-service:
    build: ./backend/stream-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  # News Crawler Service
  news-crawler:
    build: ./backend/news-crawler
    ports:
      - "3002:3002"
    env_file:
      - .env
    restart: unless-stopped

  # AI Analysis Service
  ai-service:
    build: ./backend/ai-service
    ports:
      - "3003:3003"
    env_file:
      - .env
    restart: unless-stopped

  # Alert Service
  alert-service:
    build: ./backend/alert-service
    ports:
      - "3004:3004"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
